### PR TITLE
Jason/fix dbname k8s config

### PR DESCRIPTION
**Pull request by dirkraft**
sadfjajdfkljadlfjalk

I must have looked past it 7 times.

### CODE REVIEW

**Comment by hsuhanooi** [comment]
Nice! You found it.

**Comment by dirkraft** [comment]
I have a new problem. The oracle 8 jdk install no longer works. Can't build new docker image -_-

**Comment by hsuhanooi** [comment]
lol

**Comment by dirkraft** [comment]
This is working, I see new extractions.

**Pull request merged**
